#ifndef COLORS_H_INCLUDED
#define COLORS_H_INCLUDED

#include <SDL2/SDL_pixels.h>

extern const SDL_Color COLOR_GENERIC_BUTTON_BACKGROUND;
extern const SDL_Color COLOR_GENERIC_BUTTON_BORDER;
extern const SDL_Color COLOR_GENERIC_BUTTON_BACKGROUND_HOVER;

#endif

